Raise TogglesUpdatedEvent after toggle collection is updated
Unleash/unleash-client-dotnet pull request #161
Opened 2023-09-06 23:02 UTC by YayBurritos

# Description

Raise the `TogglesUpdatedEvent` AFTER the toggles collection is update in `FetchFeatureTogglesTask`. This will allow clients that provide an event handler to be able to obtain the current toggle state rather than the "old" state.

Fixes # ([160](https://github.com/Unleash/unleash-client-dotnet/issues/160))

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Tested this by adding a project reference for `unleash-client-dotnet\src\Unleash\Unleash.csproj` to our dotnet application to verify that the event was raised and our application could see the current toggle state.

**Test Configuration**:
* IDE: Visual Studio Professional 2022 (64-bit) Version 17.4.4
* Client application that uses unleash-client-dotnet targets net 6.0

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-09-07 06:34 UTC, daveleek approved these changes
Nice catch, thank you for the bug report and the fix!
Looks good!

2023-09-07 07:00 UTC, sighphyre requested changes
Hey @YayBurritos this is a pretty great catch, thank you! Can I be a huge pain and ask if you can include a test for this? I think we got here in the first place because the sub system here wasn't well tested (we get a fair amount of PRs and I'm trying to encourage at least a few tests in community PRs going forward). 

I think  there's a few tests that poke at related sub systems in tests/Unleash.Tests/Internal/TogglesUpdatedEvent_Tests.cs and tests/Unleash.Tests/Internal/ErrorEvents_Tests.cs that can probably be a nice blueprint for this.

If it's a huge pain I can merge and add tests later. Just trying to keep the hygiene on this project up, thank you!

2023-09-07 15:27 UTC, YayBurritos commented
> Hey @YayBurritos this is a pretty great catch, thank you! Can I be a huge pain and ask if you can include a test for this? I think we got here in the first place because the sub system here wasn't well tested (we get a fair amount of PRs and I'm trying to encourage at least a few tests in community PRs going forward).
> 
> I think there's a few tests that poke at related sub systems in tests/Unleash.Tests/Internal/TogglesUpdatedEvent_Tests.cs and tests/Unleash.Tests/Internal/ErrorEvents_Tests.cs that can probably be a nice blueprint for this.
> 
> If it's a huge pain I can merge and add tests later. Just trying to keep the hygiene on this project up, thank you!

@sighphyre : I had started down the path of writing a test for this, but got stuck. Let me revisit and see if I can put something together that would validate the correct/expected behavior here. We're dealing with some app issues on our side right now, so could be a bit until I'm able to add a test. But we're anxious to have this fix so I'll do my best. Thanks for the suggestion!

2023-09-07 17:27 UTC, YayBurritos commented
@sighphyre : I added a test. Seems to be verifying the timing properly. If you have any additional suggestions, please let me know. Thanks!

2023-09-08 07:13 UTC, sighphyre approved these changes
Nice! LGTM!

2023-09-08 07:14 UTC, sighphyre commented
@YayBurritos Ah, thank you so much, hugely appreciate the test! LGTM, gonna merge and release this!

2023-09-08 07:15 UTC, merged