#201 Added netcoreapp 3.1 target to remove dependency on Microsoft.CS…
Unleash/unleash-client-dotnet pull request #204
Opened 2024-01-22 21:51 UTC by thompson-tomo

…harp

# Description
Adds a dotnet core app 3.1 target to allow for the removal of the Microsoft.CSharp reference for that framework and newer.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Simple compilation of project for new framework and ran unit tests

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-01-24 09:47 UTC, daveleek requested changes
Thank you for your contribution @thompson-tomo! I would like you to change the .NET framework version you're adding to one that's still supported, like .NET 6.

This PR reminded us that we need some platform specific tests in place as well to be certain the SDK will continue to work on both .NET Framework and .NET Core platforms. I'll add an issue for that and we'll add it to planned work

2024-01-24 12:02 UTC, thompson-tomo commented on src/Unleash/Unleash.csproj
> +    <TargetFrameworks>netstandard2.0;net48;net472;net47;net461;net46;net451;net45;netcoreapp3.1</TargetFrameworks>
Not an issue from my side as my active releases are net 8. I do note most of the frameworks listed are out of support. You do have #189 to clean up framework etc.

2024-01-24 12:10 UTC, daveleek commented on src/Unleash/Unleash.csproj
> +    <TargetFrameworks>netstandard2.0;net48;net472;net47;net461;net46;net451;net45;netcoreapp3.1</TargetFrameworks>
Great, thanks @thompson-tomo!
Indeed, we're looking at which we can remove. So would be good to not add new ones to remove again.

2024-02-11 03:23 UTC, thompson-tomo commented
@daveleek is there anything outstanding from me for this MR?

2024-02-12 07:39 UTC, daveleek commented
Thank you @thompson-tomo! No you've done your part here. We're just going to add a build and a build step for verifying this continues to work on .NET Framework (windows) in the future!

2024-02-22 07:10 UTC, daveleek approved these changes
Going to merge this and verify, we have some thoughts around future improvements but it's not a blocker

2024-02-22 07:10 UTC, merged